sudo: required
services:
  - docker

before_install:
  - docker build -t olagunju/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run olagunju/react-test npm run test -- --coverage

after_success:
  - docker build -t olagunju/multi-client ./client
  - docker build -t olagunju/multi-nginx ./nginx
  - docker build -t olagunju/multi-server ./server
  - docker build -t olagunju/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push olagunju/multi-client
  - docker push olagunju/multi-nginx
  - docker push olagunju/multi-server
  - docker push olagunju/multi-worker
