sudo: required
services:
  - docker

before_install:
  - docker build -t olagunju/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true olagunju/react-test npm test -- --coverage

after_success:
  - docker build -t olagunju/multi-client ./client
  - docker build -t olagunju/multi-nginx ./nginx
  - docker build -t olagunju/multi-server ./server
  - docker build -t olagunju/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push olagunju/multi-client
  - docker push olagunju/multi-nginx
  - docker push olagunju/multi-server
  - docker push olagunju/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-358242627487
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
